import {useEffect,useRef,useState} from 'react';
import {Leaf,ArrowUpRight,ArrowDown,ArrowRight,Play,Pause,List,X,Minus,Plus,Check,ShoppingBag} from '@phosphor-icons/react';
const chapters=[
 {name:'The leaf',title:<>STEAM PRESERVES.<br/>NATURE PERFECTS.</>,copy:'A fleeting moment of steam. A lifetime of green. Freshly picked tencha, gently awakened.',image:'leaf',label:'FLASH STEAMING',value:'21',unit:'SEC',metric:'GREEN, PRESERVED',score:'90%',stats:[['HUMIDITY','90','%'],['STEAM TIME','21','SEC'],['OXIDATION','STOPPED','']]},
 {name:'The stone',title:<>SLOW STONE CREATES<br/>A FINER GREEN.</>,copy:'Granite turns. Time slows. The leaf becomes a cloud of impossibly fine, vibrant matcha.',image:'grinder',label:'PARTICLE SIZE',value:'8',unit:'μm',metric:'UNIFORMITY',score:'95%',stats:[['SLOW GROUND','30','G / H'],['FINENESS','8','μm'],['CRAFT','STONE MILLED','']]},
 {name:'The ritual',title:<>SLOW THE WORLD.<br/>WHISK THE MOMENT.</>,copy:'A little water. A gentle whisk. Find your rhythm in the space between the everyday.',image:'latte',label:'WATER TEMPERATURE',value:'78',unit:'°C',metric:'YOUR DAILY RITUAL',score:'02 min',stats:[['MATCHA','2','G'],['WATER','70','ML'],['RHYTHM','WHISK SLOWLY','']]},
 {name:'Your matcha',title:<>PURE OR LATTE?</>,copy:'One extraordinary leaf. Two ways to make it yours. Discover your everyday green.',image:'latte',label:'MADE YOUR WAY',value:'150',unit:'ML',metric:'A MOMENT FOR YOU',score:'100%',stats:[['MATCHA','2','G'],['MILK','150','ML'],['FINISH','OVER ICE','']]},
];
export function App(){
 const [active,setActive]=useState(0),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[menu,setMenu]=useState(false),[choice,setChoice]=useState('latte'),[modal,setModal]=useState(null),[quantity,setQuantity]=useState(1),[bag,setBag]=useState(0),[added,setAdded]=useState(false);
 const dialog=useRef(null),wheel=useRef(0),touch=useRef(null),elapsed=useRef(0);const chapter=chapters[active];
 const select=i=>{setActive(Math.max(0,Math.min(3,i)));setProgress(0);elapsed.current=0;setMenu(false);setPlaying(false);};
 useEffect(()=>{if(!playing)return;let last=performance.now(),frame;const run=now=>{elapsed.current+=(now-last)/8500;last=now;if(elapsed.current>=1){setActive(a=>(a+1)%4);elapsed.current=0;}setProgress(elapsed.current);frame=requestAnimationFrame(run);};frame=requestAnimationFrame(run);return()=>cancelAnimationFrame(frame);},[playing]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{const scroll=e=>{if(modal||menu||Math.abs(e.deltaY)<15||Date.now()-wheel.current<1100)return;wheel.current=Date.now();select(active+(e.deltaY>0?1:-1));};const keys=e=>{if(modal||menu||/INPUT|BUTTON|SELECT/.test(e.target.tagName))return;if(['ArrowDown','ArrowRight'].includes(e.key)){e.preventDefault();select(active+1);}if(['ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();select(active-1);}};window.addEventListener('wheel',scroll,{passive:true});window.addEventListener('keydown',keys);return()=>{window.removeEventListener('wheel',scroll);window.removeEventListener('keydown',keys);};},[active,modal,menu]);
 const openOrder=()=>{setAdded(false);setModal('order');setMenu(false);};
 return <main className={`experience chapter-${active} ${choice}`} onTouchStart={e=>touch.current=e.touches[0].clientY} onTouchEnd={e=>{if(modal||menu||touch.current===null)return;const d=touch.current-e.changedTouches[0].clientY;if(Math.abs(d)>65)select(active+(d>0?1:-1));}}>
 <div className="scene-stack" aria-hidden="true">{chapters.map((c,i)=><div className={`scene ${i===active?'is-active':''}`} key={i}><img src={`./assets/${c.image}.webp`} alt=""/><div className="shade"/></div>)}</div>
 <div className="announcement">An extraordinary leaf. An everyday ritual. <button onClick={()=>setModal('origins')}>Discover MORI <ArrowUpRight size={11}/></button></div>
 <header><button className="brand" onClick={()=>select(0)} aria-label="Mori Matcha Lab home"><span className="brand-mark"><Leaf weight="thin"/></span><span>MORI<small>MATCHA LAB</small></span></button><nav aria-label="Main navigation"><button className={active===0?'current':''} onClick={()=>select(0)}>HOME</button><button onClick={()=>setModal('origins')}>OUR STORY</button><button className={active===1?'current':''} onClick={()=>select(1)}>THE PROCESS</button><button className={active>1?'current':''} onClick={()=>select(2)}>THE RITUAL</button><button onClick={()=>setModal('contact')}>CONTACT</button></nav><div className="header-actions"><button className="pill order" onClick={openOrder}>{bag?`BAG (${bag})`:'ORDER MATCHA'}<ArrowUpRight size={14}/></button><button className="icon" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></div></header>
 <section className="chapter-content" aria-label={chapter.name} key={active}><p className="eyebrow">0{active+1} / {['PRESERVE','REFINE','AWAKEN','ENJOY'][active]}</p><h1>{chapter.title}</h1><p className="description">{chapter.copy}</p>{active===3?<><div className="choices" aria-label="Choose your matcha"><button aria-pressed={choice==='pure'} onClick={()=>setChoice('pure')}>PURE</button><button aria-pressed={choice==='latte'} onClick={()=>setChoice('latte')}>LATTE</button></div><p className="recipe">{choice==='pure'?'2 g matcha · 70 ml water · whisk until silky':'2 g matcha · 150 ml milk · pour over ice'}</p><button className="pill" onClick={openOrder}>MAKE IT A RITUAL <ArrowUpRight size={15}/></button></>:<button className="text-link" onClick={()=>select(active+1)}>FOLLOW THE LEAF <ArrowRight size={18}/></button>}</section>
 <aside className="readouts" key={`readout-${active}`} aria-label="Process details"><div className="measure"><span>{chapter.label}</span><strong>{active===3&&choice==='pure'?'70':chapter.value}<small>{chapter.unit}</small></strong></div><div className="purity"><span>{chapter.metric}</span><strong>{chapter.score}</strong><div className="spectrum" aria-hidden="true">{Array.from({length:26},(_,i)=><i key={i} style={{height:`${15+((i*17+i*i*3)%70)}%`,animationDelay:`${i*.07}s`}}/>)}</div></div><p className="readout-foot">MORI / PRECISION IN EVERY DETAIL</p></aside>
 <aside className="chapter-rail" aria-label="Chapters"><span>0{active+1}</span><span className="vertical">LEAF TO RITUAL</span><div className="rail-line">{chapters.map((c,i)=><button key={c.name} aria-label={c.name} aria-current={i===active?'step':undefined} onClick={()=>select(i)}>{i===active?`0${i+1}`:<span/>}</button>)}</div><span>04</span></aside>
 <footer><div className="stats">{chapter.stats.map(([label,value,unit],i)=><div key={label}><span>{active===3&&choice==='pure'&&i===1?'WATER':label}</span><strong>{active===3&&choice==='pure'&&i===1?'70':active===3&&choice==='pure'&&i===2?'SILKY FOAM':value}<small>{unit}</small></strong></div>)}</div><div className="playback"><button className="icon" aria-label={playing?'Pause tour':'Play tour'} onClick={()=>setPlaying(!playing)}>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</button><span>{playing?'THE JOURNEY IS UNFOLDING':'SCROLL TO EXPLORE'}</span><button className="icon next" aria-label={active===3?'Return to the leaf':'Next chapter'} onClick={()=>select((active+1)%4)}><ArrowDown/></button></div></footer><div className="bottom-track"><span style={{width:`${(active+progress+1)/4*100}%`}}/></div>
 {menu&&<div className="menu-panel"><p>THE WORLD OF MORI</p>{chapters.map((c,i)=><button key={c.name} onClick={()=>select(i)}><small>0{i+1}</small>{c.name}<ArrowUpRight/></button>)}<button className="menu-story" onClick={()=>{setMenu(false);setModal('origins')}}>Our story</button></div>}
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><button className="close icon" aria-label="Close dialog" onClick={()=>setModal(null)}><X/></button>{modal==='order'?<><p className="eyebrow">MORI MATCHA LAB / FIRST HARVEST</p><h2>A little green.<br/>A daily ritual.</h2><div className="product"><img src="./assets/leaf.webp" alt="Fresh matcha leaf inside a glass steaming chamber"/><div><h3>Ceremonial matcha</h3><p>First-harvest tencha · Stone milled<br/>30 g / approximately 15 rituals</p><strong>₹1,490</strong></div></div><div className="quantity"><span>QUANTITY</span><div><button aria-label="Decrease quantity" disabled={quantity===1} onClick={()=>setQuantity(quantity-1)}><Minus/></button><output>{quantity}</output><button aria-label="Increase quantity" disabled={quantity===9} onClick={()=>setQuantity(quantity+1)}><Plus/></button></div></div><button className="add-button" disabled={added} onClick={()=>{setBag(b=>b+quantity);setAdded(true)}}>{added?<><Check/> ADDED TO YOUR BAG</>:<><ShoppingBag/> ADD TO BAG · ₹{(1490*quantity).toLocaleString('en-IN')}</>}</button><p className="demo-note">A concept store. Your bag is a preview; no payment or order is placed.</p></>:modal==='contact'?<><p className="eyebrow">LET'S TALK TEA</p><h2>Good things<br/>begin together.</h2><p>Questions about your ritual? Curious about the leaf? Explore our story and the journey from tencha to your cup.</p><button className="add-button" onClick={()=>setModal('origins')}>MEET MORI <ArrowUpRight/></button><p className="demo-note">This concept website has no connected contact service.</p></>:<><p className="eyebrow">THE MORI PHILOSOPHY</p><h2>Less hurry.<br/>More green.</h2><p>MORI is a study in the quiet craft of matcha. From the fresh green leaf to the slow-turning stone, every stage makes room for care.</p><p>Our lab brings that journey into view. Explore the process, find your recipe, and make a little space for your daily ritual.</p><button className="add-button" onClick={()=>{setModal(null);select(1)}}>EXPLORE THE PROCESS <ArrowRight/></button></>}</dialog>
 </main>;
}
